image: golang:alpine

variables:
  REPO_NAME: agamigo.io/material

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - apk add -U git yarn
  - go get -u github.com/gopherjs/gopherjs
  - yarn install

stages:
    - test

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - gopherjs test $(go list ./... | grep -v /vendor/)